### ISSUE TITLE
Criar estrutura do projeto

### ISSUE THREAD

**Issue by Diego-Brocanelli** [DeveloperSpace/DateTools#1]
# Implementar
    - composer.json
         : Configurar estrutura geral
         : Configurar autoload.
         : Configurar dependência: 
             * PHPUnit
         : Configurar required:
              * PHP 5.3.8
    -  Criar estrutura do projeto
        : src
            * Date
                # Validation
                    BR
                        isValid :return boolean
                        isEmpty :return boolean
                # Convertion
                    BR
                        convert :return string/execption
                # Operation
                    BR
                        timestampFriendly :return string/execption
                        sum :return string/execption
                        sub :return string/execption
                        diff :return string/execption
    - .gitignore
        : nbproject
        : vendor
    - tests

**Comment by renanliberato** [comment]
Issue referenciada no pull request #10 já mergeado.
